### ISSUE TITLE
Process crashing due to fdisk command giving empty response

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#107]
Hi, 

I am moving issue https://github.com/TuxML/Core/issues/2 (Core repository) here, since it's the right place. 
Experiments show that sometimes it fails, sometimes it is working. @mipicard succeeded, I succeeded today (MacOS), and most of us have failures. 

An hypothesis we can make is that some material is not recognized by fdisk (perhaps SSD disks). 
Anyway we need to fix it ;-) 

The line in question is here:
https://github.com/TuxML/ProjetIrma/blob/dev/core/tuxml_environment.py#L152 

if fdisk returns nothing, then I can imagine some troubles and it most likely explain the failure...
So **first task**: we need to make the function more robust. 
I suggest two things:
 * having a defensive approach in which we raise an exception and catch it (we should inform the user with a big warning... and we send no information related to the disk to the database) 
 * then correct the line in question in such a way it works well 

The **second task** is to commit/push the solution and then update the Docker image, following instructions here: https://github.com/TuxML/ProjetIrma/wiki/How-To-(Main-questions)#how-to-update-the-docker-image 

(side note: the Core project is *not* the Docker image, it was misleading but it is clearly not the case) 

The **third task** is to all make experiments using the new Docker image and see if it's working.

**Comment by FAMILIAR-project** [comment]
Strange experience I've got similar error:

```
>>> subprocess.check_output("fdisk -l | grep Disk -m1", shell=True).decode().split()[1].split("/")[2].strip(":")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'fdisk -l | grep Disk -m1' returned non-zero exit status 1
>>> subprocess.check_output("fdisk -l | grep Disk -m1", shell=True).decode().split()[1].split("/")[2].strip(":")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'fdisk -l | grep Disk -m1' returned non-zero exit status 1
```

when using the Docker image. 
It's strange because I succeed to compile on my machine!!  

Anyway, maybe we should use something like psutil (not a standard package): 
https://psutil.readthedocs.io/en/latest/

and psutil.disk_partitions() that sounds more robust and interoperable
