### ISSUE TITLE
Tuxml version

### ISSUE THREAD

**Issue by FAMILIAR-project** [TuxML/ProjetIrma#132]
Just a try:
`python3 kernel_generator.py --tiny --dev --linux4_version 4.20.1 1`

strange no?
`Step 2/4 : RUN tar xf /TuxML/linux-4.13.3.tar.xz -C /TuxML && rm /TuxML/linux-4.13.3.tar.xz`

it seems the parsing of the version number fails 
```
Building specific image for linux v4.4.20.1 ...
Linux kernel not found, downloading...
--2019-03-27 13:49:10--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.20.1.tar.xz
R'esolution de cdn.kernel.org (cdn.kernel.org)... 151.101.1.176, 151.101.65.176, 151.101.129.176, ...
Connexion `a cdn.kernel.org (cdn.kernel.org)|151.101.1.176|:443... connect'e.
requ^ete HTTP transmise, en attente de la r'eponse... 404 Not Found
2019-03-27 13:49:11 erreur 404 : Not Found.

Traceback (most recent call last):
  File "kernel_generator.py", line 645, in <module>
    tag = docker_build_v4_image(tag, args.linux4_version)
  File "kernel_generator.py", line 423, in docker_build_v4_image
    get_linux_kernel(linux_kernel[:-7])
  File "kernel_generator.py", line 457, in get_linux_kernel
    subprocess.run(args=wget_cmd, shell=True, check=True)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'wget https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.20.1.tar.xz' returned non-zero exit status 8.
```

**Comment by FAMILIAR-project** [comment]
My bad:
kernel_generator.py --tiny --linux4_version 20.1 --dev 1 

(without 4.)
