### ISSUE TITLE
Decompression failure

### ISSUE THREAD

**Issue by mipicard** [TuxML/ProjetIrma#139]
When we download the image for the first time, it can happen that the decompression fail.
```bash
The command '/bin/sh -c tar xf /TuxML/linux-4.13.3.tar.xz -C /TuxML && rm /TuxML/linux-4.13.3.tar.xz' returned a non-zero code: 2
Updating of docker image done.

=============== Docker number  0  ===============
Unable to find image 'tuxml/tuxml:dev' locally
docker: Error response from daemon: pull access denied for tuxml/tuxml, repository does not exist or may require 'docker login'.
See 'docker run --help'.
Traceback (most recent call last):
 File "kernel_generator.py", line 653, in <module>
   compilation(image, args)
 File "kernel_generator.py", line 579, in compilation
   args.number_cpu
 File "kernel_generator.py", line 486, in run_docker_compilation
   shell=True
 File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
   **kwargs).stdout
 File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
   output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'docker run -i -d tuxml/tuxml:dev' returned non-zero exit status 125.
```

Thankfully, another run fix this error.
But we should try to handle this error without having the user to try again.

**Comment by mipicard** [comment]
This error is linked with this previous issue https://github.com/TuxML/ProjetIrma/issues/129

**Comment by mipicard** [comment]
As stated with the previous issue, it's an internal error when uncompressing. It looks like tar wanted to uncompress too fast and crash itself.

An idea would be to wrap the decompression with a script who will do the job for us (it will retry everytime tar return errorcode 2)

**Comment by mipicard** [comment]
Some documentation about tar :

> 2      Fatal error.  This means that some fatal, unrecoverable error
              occurred.

       If a subprocess that had been invoked by tar exited with a nonzero
       exit code, tar itself exits with that code as well.  This can happen,
       for example, if a compression option (e.g. -z) was used and the
       external compressor program failed.  Another example is rmt failure
       during backup to a remote device.

And it look like it's this case here.

**Comment by mipicard** [comment]
Important note : if we do add a wrapper script, both master and dev branch, along with both prod and dev image will have to updated in order to keep consistency.
