### ISSUE TITLE
BdD hors-service

### ISSUE THREAD

**Issue by Heartbroken-Git** [TuxML/ProjetIrma#7]
La base de données JHispter ne fonctionne plus.
La machine et le site sont accessibles. Cependant la base en elle même ne l'est pas. On ne peut plus accéder à son contenu ou l'éditer.

D'où l'issue #6.

**Comment by micleb** [comment]
C'est toujours d'actu :(
![firefox](https://i.imgur.com/55VxVy7.png)

Et quand j'ai voulu envoyer une compil' : 
```
[+] 2017-11-15 19:50:00 | Successfully compiled in 00:07:59, sending data
[*] Sending config file and status to database
Traceback (most recent call last):
  File "./tuxml.py", line 272, in <module>
    sendDB.send_data(tuxml_settings.PATH, tuxml_settings.ERR_LOG_FILE, status)
  File "/home/micleb/Documents/TUXML/sendDB.py", line 60, in send_data
    conn_http.request("POST", "/api/authenticate", auth_body, auth_header)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by Heartbroken-Git** [comment]
Ok, alors la nouvelle BdD LAMP est opérationnelle mais il y a un nouveau problème. @PLeLuron n'arrive pas à interagir par son script avec elle.

**Comment by ghost** [comment]
Réglé dans dev
