### ISSUE TITLE
TUXML colors (crash) 

### ISSUE THREAD

**Issue by acherm** [TuxML/ProjetIrma#71]
Traceback (most recent call last):
  File "/TuxML/tuxml.py", line 285, in <module>
    main()
  File "/TuxML/tuxml.py", line 258, in main
    if init_launcher() != 0:
  File "/TuxML/tuxml.py", line 116, in init_launcher
    tset.TUXML_ENV = tenv.get_environment_details()
  File "/TuxML/tuxml_environment.py", line 293, in get_environment_details
    environment_pprinter(env)
  File "/TuxML/tuxml_environment.py", line 268, in environment_pprinter
    print(tset.COLORS["gray"] + " " * 4 + "==> "+ dico)
AttributeError: module 'tuxml_settings' has no attribute 'COLORS'

**Comment by acherm** [comment]
I am handling this issue. Should be tset.GRAY

**Comment by acherm** [comment]
Fixed
